baseURL = "https://bramaudi.my.id/"
languageCode = "id-ID"
title = "bramaudi"
enableEmoji = true
pygmentsUseClasses = true
#PygmentsStyle = "api"
#Paginate = 2
summaryLength = 5

[params]
  description = "Personal Blog, topik suka-suka."

[menu]

  [[menu.main]]
    weight = 1
    name = "tentang"
    url = "/tentang/"

  [[menu.main]]
    weight = 2
    name = "github"
    url = "http://github.com/bramaudi"