title: bramaudi.dev
description: I am person that write stuff.
author:
  name: Brama Udi
  email: bramaudi.al@gmail.com
  description:
    Seorang kuli & penikmat kopi, suka menggambar pixelart,
    bisa ngetik, bisa pemrogramman (web), bisa desain,
    bisa mencintaimu dengan apa adanya tanpa kenal lelah.
