version: 2.0

jobs:
    build:
        docker:
            - image: felicianotech/docker-hugo:latest
        working_directory: ~/bramaudi.github.io
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "1d:bf:e1:4b:15:75:37:0d:0b:af:a4:21:fa:a0:dc:b8"
            - checkout
            - run:
                name: Get current site
                working_directory: ~/
                command: git clone -b master git@github.com:bramaudi/bramaudi.github.io.git public
            - run:
                name: Generate site
                working_directory: ~/bramaudi.github.io
                command: HUGO_ENV=production hugo -d ~/public
            - deploy:
                name: Deploy to Github Pages
                working_directory: ~/public
                command: |
                    git config credential.helper 'cache --timeout=120'
                    git config user.email "bramaudi@users.noreply.github.com"
                    git config user.name "Deployment Bot"
                    git add .
                    git commit --allow-empty -m "Trigger deployment"
                    git push -q git@github.com:bramaudi/bramaudi.github.io.git master                    

workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          branches:
            only: source